FROM node:12

# Create app directory
WORKDIR /usr/src/app

# Create temporary files directory
RUN mkdir /usr/src/tmp

# Install app dependencies
COPY package.json ./
COPY yarn.lock ./

# Update repositories
RUN apt-get update

# Install ffmpeg dependency
RUN apt-get install ffmpeg

RUN npm install -g yarn
RUN yarn install
# If you are building your code for production
# RUN yarn install --production

# Bundle app source
COPY . .

EXPOSE 8080
CMD [ "yarn", "start" ]