export const WINDOW_RESIZED = 'WINDOW_RESIZED';
export const SET_NAVIGATOR_ONLINE = 'SET_NAVIGATOR_ONLINE';
export const SET_VIEWMODE = 'SET_VIEWMODE';
export const SET_USER_LANGUAGE = 'SET_USER_LANGUAGE';
export const SET_CURRENT_TIME = 'SET_CURRENT_TIME';

export default [
  WINDOW_RESIZED,
  SET_NAVIGATOR_ONLINE,
  SET_USER_LANGUAGE,
  SET_VIEWMODE,
  SET_CURRENT_TIME
];
