export const WINDOW_RESIZED = 'WINDOW_RESIZED';
export const SET_NAVIGATOR_ONLINE = 'SET_NAVIGATOR_ONLINE';
export const SET_VIEWMODE = 'SET_VIEWMODE';
export const SET_USER_LANGUAGE = 'SET_USER_LANGUAGE';
export const SET_CURRENT_TIME = 'SET_CURRENT_TIME';
export const SET_SERIES_CATEGORIES = 'SET_SERIES_CATEGORIES';
export const SET_SERIES_CURRENT_CATEGORY = 'SET_SERIES_CURRENT_CATEGORY';
export const SET_SERIES_CATEGORY_SERIES = 'SET_SERIES_CATEGORY_SERIES';
export const ADD_IMAGE = 'ADD_IMAGE';
export const SET_SERIES_CURRENT_SERIE = 'SET_SERIES_CURRENT_SERIE';
export const SET_SERIES_CURRENT_SEASON = 'SET_SERIES_CURRENT_SEASON';
export const SET_SERIES_CATEGORY_SERIE_SEASONS =
  'SET_SERIES_CATEGORY_SERIE_SEASONS';
export const SET_SERIES = 'SET_SERIES';
export default [
  WINDOW_RESIZED,
  SET_NAVIGATOR_ONLINE,
  SET_USER_LANGUAGE,
  SET_VIEWMODE,
  SET_CURRENT_TIME,
  SET_SERIES_CATEGORIES,
  SET_SERIES_CURRENT_CATEGORY,
  SET_SERIES_CATEGORY_SERIES,
  ADD_IMAGE,
  SET_SERIES_CURRENT_SERIE,
  SET_SERIES_CURRENT_SEASON,
  SET_SERIES_CATEGORY_SERIE_SEASONS,
  SET_SERIES
];
